version: "3.8"
services:
  bot:
    build: .
    container_name: my-telegram-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./videos:/home/appuser/videos
    restart: unless-stopped
